# Generated by Django 3.0.7 on 2020-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200608_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
