# Generated by Django 3.0.7 on 2020-06-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
